name: collect-polymarket

on:
  schedule:
    - cron:  '0 6 * * *'    # roda todos os dias às 06:00 UTC :contentReference[oaicite:2]{index=2}
  workflow_dispatch:         # botão “Run workflow” manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python fetch.py
      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "auto: update dump" || echo "Nada novo"
          git push
